spring:
  application:
    name: event-orchestrator
  # Para que tome Config Server desde env
  config:
    import: optional:configserver:${SPRING_CONFIG_IMPORT:}
  
  # Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    
management:
  endpoints.web.exposure.include: health,info,metrics,kafka

server:
  port: 8084
